### PR TITLE
Patch for duplicate functions

### PR DESCRIPTION
**Pull request by Erotemic**
Attempts to fix: https://github.com/pyutils/line_profiler/issues/232

Adds in tests and also contains other code cleanup.

### CODE REVIEW

**Comment by Erotemic** [comment]
@Theelx @notEvil One of the new tests related to duplicate functions is not passing on OSX, and I'm not sure why. It works on locally for me on Linux. 

The invocation for the test in question is:

```bash
pytest -sv tests/test_explicit_profile.py -k test_explicit_profile_with_duplicate_functions
```

If either of you has an OSX device to test on, or can offer insights that would be helpful. 

Could it be the case that the patch should only be applied to 3.11? (The 3.6 test is failining here and I'm not sure if other versions would pass).

**Comment by notEvil** [comment]
I don't, sry. As for the fix, maybe use `.to_bytes(2, ...` instead of `* 2` to be safe.

**Comment by Theelx** [comment]
> @Theelx @notEvil One of the new tests related to duplicate functions is not passing on OSX, and I'm not sure why. It works on locally for me on Linux.
> 
> The invocation for the test in question is:
> 
> ```shell
> pytest -sv tests/test_explicit_profile.py -k test_explicit_profile_with_duplicate_functions
> ```
> 
> If either of you has an OSX device to test on, or can offer insights that would be helpful.
> 
> Could it be the case that the patch should only be applied to 3.11? (The 3.6 test is failining here and I'm not sure if other versions would pass).

I do not have an OSX device, sorry. I think it is reasonable to only apply the patch to 3.11.

**Comment by Theelx** [comment]
> I don't, sry. As for the fix, maybe use `.to_bytes(2, ...` instead of `* 2` to be safe.

I don't think that's a good idea, as it'll just apply padding bytes with a value of 0 to the front of the bytecode, rather than padding with values of 9. See the docs for the length option [here](https://docs.python.org/3/library/stdtypes.html?highlight=to_bytes#int.to_bytes).

**Comment by Erotemic** [comment]
The version condition didn't work. 

Disabling OSX shows that everything else is passing. Going to check if it OSX with other versions also fails.

**Comment by Erotemic** [comment]
The failing test in question is running the following code: 

```python
from line_profiler import profile

@profile
def func1(a):
    return a + 1

@profile
def func2(a):
    return a + 1

@profile
def func3(a):
    return a + 1

@profile
def func4(a):
    return a + 1

print(func1.__code__.co_code)
print(func2.__code__.co_code)
print(func3.__code__.co_code)
print(func4.__code__.co_code)

print(func1.__wrapped__.__code__.co_code)
print(func2.__wrapped__.__code__.co_code)
print(func3.__wrapped__.__code__.co_code)
print(func4.__wrapped__.__code__.co_code)

import ubelt as ub
print('profile._profile.code_map = {}'.format(ub.urepr(profile._profile.code_map, nl=1)))
for k, v in profile._profile.code_map.items():
    print(k.co_code)

func1(1)
func2(1)
func3(1)
func4(1)
```

The check is just that each of the 4 functions appear in the profile output: 

```python
assert 'Function: func1' in raw_output
assert 'Function: func2' in raw_output
assert 'Function: func3' in raw_output
assert 'Function: func4' in raw_output
```

The test includes debuggine lines to show the modified code binary. On OSX the dashboards show:

```
b'|\x00d\x01\x17\x00S\x00'
b'|\x00d\x01\x17\x00S\x00\t\x00\t\x00'
b'|\x00d\x01\x17\x00S\x00\t\x00\t\x00\t\x00'
b'|\x00d\x01\x17\x00S\x00\t\x00\t\x00\t\x00\t\x00'
```

But when I run on my linux machine the binary I get for the 4 functions is:

```
b'\x97\x00|\x00d\x01z\x00\x00\x00S\x00'
b'\x97\x00|\x00d\x01z\x00\x00\x00S\x00\t\t\t\t'
b'\x97\x00|\x00d\x01z\x00\x00\x00S\x00\t\t\t\t\t\t'
b'\x97\x00|\x00d\x01z\x00\x00\x00S\x00\t\t\t\t\t\t\t\t'
```

Does anything about these outputs give any hints?

**Comment by Erotemic** [comment]
I think I figured it out. It was an unrelated issue. For some reason on OSX the measured time was zero, which meant it was filtered out by the stripzero condition. I change stripzero to look for zero hits instead of zero time, which is probably the correct behavior anyway. That seems to resolve the issue.

**Pull request merged**
