### PR TITLE
Use ns resolution on non-Windows/OS2

### PR DESCRIPTION
**Pull request by utkarshgupta137**

### CODE REVIEW

**Comment by Theelx** [comment]
I actually attempted this independently when preparing for #165, but when I did some research, it turns out that nanosecond resolution isn't the same as nanosecond accuracy. One nanosecond is only 4 clock cycles on a CPU that runs at 4GHz, and even simple Python lines can easily be hundreds to thousands of clock cycles. If this was a resolution of 100ns, that could be reasonable, but for now 1 microsecond makes the most sense, if only to keep it consistent between platforms.

**Comment by utkarshgupta137** [comment]
The point of this change is not to get ns resolution but to get 1 extra digit of significance. Plenty of python statements take less then 1 microsecond (around half). So, getting 0.2 or 0.9 instead of 0 or 1 can be useful.
If you try out the change, you'll notice that the scale is still microsecond, but you're seeing a single decimal digit as well.

**Comment by utkarshgupta137** [comment]
I think this is also the reason why `time.perf_counter` uses the highest available resolution.

**Comment by Erotemic** [comment]
I think we should look at incorporating this.

**Comment by Theelx** [comment]
I forgot to mention, I incorporated it into #165 around September 20th I believe.

**Comment by Erotemic** [comment]
Resolved in a different branch.

**Pull request closed without merging**
