### PR TITLE
Add circleci

### PR DESCRIPTION
**Pull request by Erotemic**
TravisCI is shutting down. We need to migrate to a new CI platform. CircleCI is a pretty good one.

### CODE REVIEW

**Comment by Mogost** [comment]
@Erotemic Why do you prefer CircleCI over GitHub Actions?

**Comment by Erotemic** [comment]
@Mogost I've never used Github actions. I have experience with CircleCI.

**Comment by Mogost** [comment]
If that's the only reason, I'd recommend you take a look at GitHub Action. Not much difference in principle, yml files, similar configurations.
In my opinion, the story that happened with Travis is more likely to repeat itself on CircleCI than on GitHub.
One more advantage is that in fact you replace two tools (Github+CircleCI) with one (GitHub).

**Comment by Erotemic** [comment]
I will look into it. I think its usually worth having multiple CI services anyway.

**Comment by Erotemic** [comment]
Closing in favor of #48

**Pull request closed without merging**
