### PR TITLE
Add render web report

### PR DESCRIPTION
**Pull request by mirecl**
**AS-IS:** in version ``3.4.0`` formatting report in ``stdout``, for example:
**Run kernprof:**
```bash
(venv) mirecl@terminal % kernprof -l app.py                               
Wrote profile results to app.py.lprof
```
**Run line_profiler for render report in stdout**
```bash
(venv) mirecl@terminal % python -m line_profiler app.py.lprof  -u 0.001
Timer unit: 0.001 s

Total time: 1.812 s
File: app.py
Function: do_stuff at line 17

Line #      Hits         Time      Per Hit   % Time       Line Contents
=======================================================================
    17                                                    @profile
    18                                                    def do_stuff():
    19         1          3.7          3.7      0.2           numbers = [random.randint(1, 100) for i in range(1000)]
    20         1       1807.2       1807.2     99.7           do_other_stuff(numbers)
    21         1          0.4          0.4      0.0           l = [numbers[i] / 43 for i in range(len(numbers))]
    22         1          0.7          0.7      0.0           m = ["hello" + str(numbers[i]) for i in range(len(numbers))]
```
**TO-BE:** in version ``3.5.0`` add new flag -w for web render.
```bash
(venv) mirecl@terminal % python -m line_profiler app.py.lprof  -u 0.001 -w
```
Auto open default browser with report:
Screenshot 2022-03-17 at 13 08 31

### CODE REVIEW

**Comment by Nodd** [comment]
Why have a static page with the same content as the console, while you can have a full blown interactive GUI like  https://github.com/Nodd/lineprofilergui ?
Full disclaimer : I'm the author of Line Profiler GUI

Outside of my shameless ad, what functionality would bring such a web interface ? To store the output in a human readable way ?
If it's the case, you can also do something like:

    python -m line_profiler app.py.lprof  -u 0.001 > results.txt

**Comment by mirecl** [comment]
@Nodd thanks for the help and the idea, but I prefer the Web GUI more than the Desktop GUI.
@Erotemic I agree about the idea with tool that is built on top of ``line_profiler``.

Today a publish new package ``pprof`` (https://pypi.org/project/pprof/) with support web render report and profiling async func.

Later, I want add support:

- memory_profiler (https://pypi.org/project/memory-profiler/)
- gprof2dot (https://pypi.org/project/gprof2dot/)

@Erotemic , @Nodd  Do you mind if I add ``pprof`` to list of 3rd party tools built on cProfile or ``line_profiler`` in README.rst?

**Comment by Erotemic** [comment]
@mirecl Your `pprof` api looks nice. I like it a lot. I'm a big fan of not using a magically injected `profile` decorator.

I want to ensure that project I link to here are either mature and widely used _or_ that they have good software practices. Your project is pip installable so that's a good first step, but what I'd like to see is that your project has a CI workflow that gives users confidence that installing it is going to work out of the box without issue. If you add tests, CI, (and ideally some badges showing that tests are passing and reporting reasonable coverage numbers), I'll add a link in the README.

**Comment by mirecl** [comment]
@Erotemic, I agree with you on everything.

Add:
* Test
* CI
* badges.

Create new PR: #138

**Pull request closed without merging**
