### PR TITLE
Scikit-build + Wheels + GPG + PyPI

### PR DESCRIPTION
**Pull request by Erotemic**
Working on setting up scikit-build for binary dependencies.

### CODE REVIEW

**Comment by Erotemic** [comment]
@Mogost or @Hanaasagi can either of use review this PR and give it a thumbs up/down. 

It is a bit of a bigger change than I wanted it to be. I changed the build process to use CMake and scikit-build, which should make it easier to build wheels on each platform. To do this I had to restructure the module so it was in a package structure instead of pure files (kernprof.py is still a standalone file). Despite this change, the installed package should still work the same. I ensured that the `__init__.py` exposed all the functionality of the original `line_profiler.py`. 

The requirements are now listed in a requirements.txt and a requirements folder and the README now displays badges. There is a pyproject.toml with the appropriate pre-setup requirements. 

I also added `run_multibuild.sh`, which uses docker to build manylinux wheels.

I also added a `publish.sh` script which will be able to create and push manylinux wheels and source tarballs to pypi (pending the transfer of name). I created a GPG key  (1636DAF294BA22B89DBB354374F166CFA2F39C18) for the PyUtils organization, and I've added encrypted versions of the private keys to the repo. These are decrypted on travis and used to sign and publish wheels to pypi whenever the release branch is built. 

I don't know how to automate wheels for win32, and I haven't been 100% successful building mac wheels in the past, so if either of you (or anyone else) knows how to do this I'd be interested in learning. 

This also bumps the version of line_profiler to 3.0.0 to reflect the change in ownership. 

I'm not sure what the best way to handle choosing to merge PRs with multiple ownership is right now. Until we figure that out I'd like to get at least one other ok before I merge something.

**Comment by Mogost** [comment]
@Erotemic I'm not so good with travis, but apparently [this project](https://github.com/mavlink/MAVSDK-Python) has done well for linux / windows / macos.

**Comment by Hanaasagi** [comment]
Not familiar with scikit. But it looks good if we can build manylinux pacage.

**Comment by Mogost** [comment]
Also I see warnings in travis
> Build config validation 
> root: deprecated key sudo (The key `sudo` has no effect anymore.)
> root: missing os, using the default linux

**Comment by Erotemic** [comment]
Ok, I think this is ready. I've fixed a few remaining bugs, rebased on the latest master, gotten 3.8 manylinux wheels working, and squashed into a reasonable number of commits. 

After this PR is merged, then any subsequent merge into the "release" branch should trigger TravisCI to push the latest wheels to pypi. We should wait until the transfer of the pypi repo is complete before we merge into release, but this branch can be merged into master in the meantime.

Note, this PR does not add osx or win32 binary wheels (although source tarballs and universal wheels will be available), so adding support for those operating systems can be left to another PR. 

@Mogost, I don't see the warnings you were talking about. I searched the logs, but I didn't see them. Can you either link me or verify that they are fixed? If they look good can you hit the merge button (to test that I setup permissions correctly)?

**Comment by Mogost** [comment]
@Erotemic https://travis-ci.org/pyutils/line_profiler/builds/624906590/config
I am talking about
image
These are just warnings, I think it can be ignored.

**Pull request merged**
